# continuous deployment (use lambda)

version: 0.2

phases:
  install:
    commands:
      - cd lambda/custom && npm install
  build:
    commands:
      - npm test
      - npm run package
artifacts:
  files:
    - lambda/custom/jimbo-facts.zip
